[ts] Fix some typescript errors
    demo/test.js:190:8 - error TS7023: 'check' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.

    190        check: function () { return this.pointless_checkbox_value; },
               ~~~~~

    demo/test.js:190:41 - error TS2339: Property 'pointless_checkbox_value' does not exist on type '{ check: () => any; toggle: typeof toggle; }'.

    190        check: function () { return this.pointless_checkbox_value; },
                                                ~~~~~~~~~~~~~~~~~~~~~~~~

    demo/test.js:191:35 - error TS2339: Property 'pointless_checkbox_value' does not exist on type '{ check: () => any; toggle: typeof toggle; }'.

    191        toggle: function () { this.pointless_checkbox_value = !this.pointless_checkbox_value; }
                                          ~~~~~~~~~~~~~~~~~~~~~~~~

    demo/test.js:191:68 - error TS2339: Property 'pointless_checkbox_value' does not exist on type '{ check: () => any; toggle: typeof toggle; }'.

    191        toggle: function () { this.pointless_checkbox_value = !this.pointless_checkbox_value; }
                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~