[ts/demo] Use WeakMap instead of tacking on properties for positioning
This fixes the following errors:

    demo/demo.js:208:5 - error TS18048: '_new_offset' is possibly 'undefined'.

    208     _new_offset.top !== _old_offset?.top ||
            ~~~~~~~~~~~

    demo/demo.js:209:5 - error TS18048: '_new_offset' is possibly 'undefined'.

    209     _new_offset.left !== _old_offset?.left
            ~~~~~~~~~~~

    demo/demo.js:213:12 - error TS18048: '_new_offset' is possibly 'undefined'.

    213      left: _new_offset.left,
                   ~~~~~~~~~~~

    demo/demo.js:214:11 - error TS18048: '_new_offset' is possibly 'undefined'.

    214      top: _new_offset.top,
                  ~~~~~~~~~~~