[ts] Declare AccessKeys as a constant, not just an interface
This avoids "error TS2693: 'AccessKeys' only refers to a type, but is being used as a value here."
when referencing `AccessKeys`.